<h1><center style="color:red;">Parcial Final</h1>

In [2]:
import os
import pandas as pd
import numpy as np
os.getcwd()
os.chdir("C:\\Users\\ANDRES\\Trabajos Universidad\\Estadistica\\Computacion Estadistica")
os.getcwd()

'C:\\Users\\ANDRES\\Trabajos Universidad\\Estadistica\\Computacion Estadistica'

In [14]:
#Bases de datos
a80     = pd.read_table("anime80s.csv",header=0)
a90     = pd.read_table("anime90s.csv",header=0)
a00     = pd.read_table("anime00s.csv",header=0)
a10     = pd.read_table("anime10s.csv",header=0)
animes  = pd.concat([a80,a90,a00,a10])

animes.info()
animes

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6612 entries, 0 to 3175
Data columns (total 11 columns):
MAL_ID          6612 non-null int64
Name            6612 non-null object
Genres          6576 non-null object
English name    3727 non-null object
Type            6612 non-null object
Episodes        6566 non-null float64
Aired           6612 non-null object
Studios         4996 non-null object
Source          5311 non-null object
Duration        6565 non-null object
Premiered       6612 non-null int64
dtypes: float64(1), int64(2), object(8)
memory usage: 619.9+ KB

,MAL_ID,Name,Genres,English name,Type,Episodes,Aired,Studios,Source,Duration,Premiered
0,47,Akira,"Action, Military, Sci-Fi, Adventure, Horror, S...",AKIRA,Movie,1.0,"Jul 16, 1988",Tokyo Movie Shinsha,Manga,2 hr. 4 min.,1988
1,85,Mobile Suit Zeta Gundam,"Military, Sci-Fi, Space, Drama, Romance, Mecha",Mobile Suit Zeta Gundam,TV,50.0,"Mar 2, 1985 to Feb 22, 1986",Sunrise,Original,24 min. per ep.,1985
2,86,Mobile Suit Gundam ZZ,"Space, Comedy, Mecha, Military, Drama, Sci-Fi",Mobile Suit Gundam ZZ,TV,47.0,"Mar 1, 1986 to Jan 31, 1987",Sunrise,Original,24 min. per ep.,1986
3,87,Mobile Suit Gundam: Char's Counterattack,"Military, Sci-Fi, Space, Drama, Mecha",Mobile Suit Gundam:Char's Counterattack,Movie,1.0,"Mar 12, 1988","Sunrise, Studio Hibari",Novel,1 hr. 59 min.,1988
4,210,Ranma ½,"Slice of Life, Comedy, Martial Arts, Fantasy, ...",Ranma ½,TV,161.0,"Apr 15, 1989 to Sep 25, 1992",Studio Deen,Manga,24 min. per ep.,1989
...,...,...,...,...,...,...,...,...,...,...,...
3171,43704,Tomato Confit,"Comedy, Drama",Tomato Confit,Movie,1.0,2012,NaN,Original,5 min.,2012
3172,44026,Zannen na Ikimono Jiten (2019),"Comedy, Slice of Life",NaN,TV,8.0,"Jul 29, 2019 to Aug 7, 2019",NHK Enterprises,Picture book,5 min. per ep.,2019
3173,44225,Norman the Snowman: Ashi Hoshi no Furu Yoru Ni,"Adventure, Kids, Fantasy",Norman the Snowman:On a Night of Shooting Stars,Movie,1.0,2016,NaN,Original,25 min.,2016
3174,44587,Nemurenai Yoru no Tsuki,"Adventure, Fantasy",Moon of a Sleepless Night,Movie,1.0,"Sep 5, 2015",Tecarat,Original,27 min.,2015
3175,45584,Don't Cry (Movie),"Action, Sci-Fi, Thriller",NaN,Movie,1.0,"Jul 1, 2017",NaN,Original,12 min.,2017

In [16]:
ratings = pd.read_table("animeratings.csv",header=0)
ratings.info()
ratings

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37524384 entries, 0 to 37524383
Data columns (total 3 columns):
user_id     int64
anime_id    int64
rating      int64
dtypes: int64(3)
memory usage: 858.9 MB

          user_id  anime_id  rating
0               0      3010       7
1              53      3010       8
2             198      3010       7
3             478      3010       6
4             542      3010       8
...           ...       ...     ...
37524379   259790     40671       3
37524380   281848     40671       9
37524381   283786     40671       6
37524382   281848     40672       9
37524383   289506     41277       4

[37524384 rows x 3 columns]

In [27]:
ratings2=(ratings
         .groupby(["anime_id"])
         .agg(veces=("anime_id","count"),rtgp=("rating","mean")).reset_index()
         .query("veces>=10000").reset_index(drop=True) 
         )
ratings2.info()
ratings2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 3 columns):
anime_id    992 non-null int64
veces       992 non-null int64
rtgp        992 non-null float64
dtypes: float64(1), int64(2)
memory usage: 23.4 KB

     anime_id  veces      rtgp
0           1  79714  8.763003
1           6  46970  8.243815
2           7  10224  7.409233
3          15  11570  8.090061
4          16  20124  8.266895
..        ...    ...       ...
987     39533  14063  8.163194
988     39597  28865  7.603222
989     39701  15899  6.363671
990     39940  24179  7.678771
991     40004  14230  7.308644

[992 rows x 3 columns]

In [43]:
animes2 = (ratings2
          .merge(animes,left_on="anime_id",right_on="MAL_ID",how="left")
          .query("Genres.str.contains('(^| )Action').values & Type=='TV'")
          .loc[:,["anime_id","rtgp","Name","English name","Episodes","Studios","Source","Premiered"]].reset_index(drop=True)  
          )
animes2.info()
animes2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 8 columns):
anime_id        410 non-null int64
rtgp            410 non-null float64
Name            410 non-null object
English name    380 non-null object
Episodes        410 non-null float64
Studios         410 non-null object
Source          410 non-null object
Premiered       410 non-null int64
dtypes: float64(2), int64(2), object(4)
memory usage: 25.8+ KB

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,1,8.763003,Cowboy Bebop,Cowboy Bebop,26.0,Sunrise,Original,1998
1,6,8.243815,Trigun,Trigun,26.0,Madhouse,Manga,1998
2,7,7.409233,Witch Hunter Robin,Witch Hunter Robin,26.0,Sunrise,Original,2002
3,15,8.090061,Eyeshield 21,NaN,145.0,Gallop,Manga,2005
4,18,8.149901,Initial D Fourth Stage,NaN,24.0,A.C.G.T.,Manga,2004
...,...,...,...,...,...,...,...,...
405,38524,9.032606,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,10.0,Wit Studio,Manga,2019
406,38659,7.530383,Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse...,Cautious Hero:The Hero Is Overpowered but Over...,12.0,White Fox,Light novel,2019
407,38671,7.674829,Enen no Shouboutai,Fire Force,24.0,David Production,Manga,2019
408,39597,7.603222,Sword Art Online: Alicization - War of Underworld,Sword Art Online Alicization War of Underworld,12.0,A-1 Pictures,Light novel,2019
409,39701,6.363671,Nanatsu no Taizai: Kamigami no Gekirin,The Seven Deadly Sins:Wrath of the Gods,24.0,"Studio Deen, Marvy Jack",Manga,2019

<h3 style="color:red;">Punto 1</h3>

In [46]:
#A
(animes2
.query("Premiered>= 1980 & Premiered<= 2000")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,1,8.763003,Cowboy Bebop,Cowboy Bebop,26.0,Sunrise,Original,1998
1,33,8.438694,Kenpuu Denki Berserk,Berserk,25.0,OLM,Manga,1997
2,136,8.426935,Hunter x Hunter,Hunter x Hunter,62.0,Nippon Animation,Manga,1999

In [47]:
#B
(animes2
.query("Premiered>= 1980 & Premiered<= 2000")
.sort_values(by=["rtgp"],ascending=[True]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,225,6.502191,Dragon Ball GT,Dragon Ball GT,64.0,Toei Animation,Manga,1996
1,550,7.072316,Yu☆Gi☆Oh!,NaN,27.0,Toei Animation,Manga,1998
2,1313,7.165677,Digimon Adventure 02,Digimon Adventure 02,50.0,Toei Animation,Original,2000

In [76]:
#C
(animes2
.query("Premiered>= 1980 & Premiered<= 2000")
.sort_values(by=["Episodes"],ascending=[True]).reset_index(drop=True)
.head(1) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,186,8.090127,Initial D Second Stage,Initial D Second Stage,13.0,Pastel,Manga,1999

<h3 style="color:red;">Punto 2</h3>

In [50]:
#A
(animes2
.query("Premiered>= 1990 & Premiered<= 2005")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,1,8.763003,Cowboy Bebop,Cowboy Bebop,26.0,Sunrise,Original,1998
1,801,8.587228,Koukaku Kidoutai: Stand Alone Complex 2nd GIG,Ghost in the Shell:Stand Alone Complex 2nd GIG,26.0,Production I.G,Manga,2004
2,205,8.506697,Samurai Champloo,Samurai Champloo,26.0,Manglobe,Original,2004

In [51]:
#B
(animes2
.query("Premiered>= 1990 & Premiered<= 2005")
.sort_values(by=["rtgp"],ascending=[True]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,225,6.502191,Dragon Ball GT,Dragon Ball GT,64.0,Toei Animation,Manga,1996
1,288,6.589010,Bakuten Shoot Beyblade,Beyblade,51.0,Madhouse,Manga,2001
2,1564,6.983210,Pokemon Advanced Generation,Pokemon:Advanced,192.0,OLM,Game,2002

In [55]:
#C
P50 = (animes2
.query("Premiered>= 1990 & Premiered<= 2005")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(50) 
)

(P50
.groupby(["Studios"])
.agg(veces=("Studios","count")).reset_index()
.sort_values(by=["veces"],ascending=[False]).reset_index(drop=True)
.head(1)
)

   Studios  veces
0  Sunrise      7

In [71]:
#D
P10 = (animes2
.query("Premiered>= 1990 & Premiered<= 2005")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(10) 
)

(P10
.sort_values(by=["Episodes"],ascending=[True]).reset_index(drop=True)
.loc[:,["rtgp","Name","English name","Episodes"]] 
.head(1) 
)

       rtgp                               Name    English name  Episodes
0  8.425145  Kino no Tabi: The Beautiful World  Kino's Journey      13.0

<h3 style="color:red;">Punto 3</h3>

In [58]:
#A
(animes2
.query("Premiered>= 2000 & Premiered<= 2015")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,28977,9.245648,Gintama°,Gintama Season 4,51.0,Bandai Namco Pictures,Manga,2015
1,5114,9.237010,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist:Brotherhood,64.0,Bones,Manga,2009
2,11061,9.169439,Hunter x Hunter (2011),Hunter x Hunter,148.0,Madhouse,Manga,2011

In [59]:
#B
(animes2
.query("Premiered>= 2000 & Premiered<= 2015")
.sort_values(by=["rtgp"],ascending=[True]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,19769,5.933991,Mahou Sensou,Magical Warfare,12.0,Madhouse,Light novel,2014
1,25429,6.002229,Isuca,Isuca,10.0,Arms,Manga,2015
2,15565,6.115344,Maken-Ki! Two,Maken-Ki! Two,10.0,Xebec,Manga,2014

In [68]:
#C
P50 = (animes2
.query("Premiered>= 2000 & Premiered<= 2015")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(50) 
)

(P50
.groupby(["Studios"])
.agg(veces=("Studios","count")).reset_index()
.sort_values(by=["veces"],ascending=[False]).reset_index(drop=True)
.head(1)
)

   Studios  veces
0  Sunrise      9

In [73]:
#D
P10 = (animes2
.query("Premiered>= 2000 & Premiered<= 2015")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(10) 
)

(P10
.sort_values(by=["Episodes"],ascending=[True]).reset_index(drop=True)
.loc[:,["rtgp","Name","English name","Episodes"]] 
.head(1) 
)

       rtgp                  Name        English name  Episodes
0  8.687159  Fate/Zero 2nd Season  Fate/Zero Season 2      12.0

<h3 style="color:red;">Punto 4</h3>

In [62]:
#A
(animes2
.query("Premiered>= 1980 & Premiered<= 2020")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,28977,9.245648,Gintama°,Gintama Season 4,51.0,Bandai Namco Pictures,Manga,2015
1,5114,9.237010,Fullmetal Alchemist: Brotherhood,Fullmetal Alchemist:Brotherhood,64.0,Bones,Manga,2009
2,11061,9.169439,Hunter x Hunter (2011),Hunter x Hunter,148.0,Madhouse,Manga,2011

In [63]:
#B
(animes2
.query("Premiered>= 1980 & Premiered<= 2020")
.sort_values(by=["rtgp"],ascending=[True]).reset_index(drop=True)
.head(3) 
)

,anime_id,rtgp,Name,English name,Episodes,Studios,Source,Premiered
0,31904,5.397692,Big Order (TV),NaN,10.0,Asread,Manga,2016
1,37744,5.460718,Isekai Cheat Magician,NaN,12.0,Encourage Films,Light novel,2019
2,29758,5.795612,Taboo Tattoo,Taboo Tattoo,12.0,J.C.Staff,Manga,2016

In [66]:
#C
P50 = (animes2
.query("Premiered>= 1980 & Premiered<= 2020")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(50) 
)

(P50
.groupby(["Studios"])
.agg(veces=("Studios","count")).reset_index()
.sort_values(by=["veces"],ascending=[False]).reset_index(drop=True)
.head(1)
)

   Studios  veces
0  Sunrise      6

In [75]:
#D
P10 = (animes2
.query("Premiered>= 1980 & Premiered<= 2020")
.sort_values(by=["rtgp"],ascending=[False]).reset_index(drop=True)
.head(10) 
)

(P10
.sort_values(by=["Episodes"],ascending=[True]).reset_index(drop=True)
.loc[:,["rtgp","Name","English name","Episodes"]] 
.head(1) 
)

,rtgp,Name,English name,Episodes
0,9.032606,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,10.0